### ISSUE TITLE
Change AD group which has write access

### ISSUE THREAD

**Issue by emirgens** [equinor/radix-cost-allocation#111]
Is this used??

Now the following group - fg_radix_costallocation - has write access to Cost Allocation, replace this with a new Azure AD group, managed (owners) by PO and Team lead.

- [x] Request new group, and add memebrs
- [x] Update application with the new group
- [x] Delete existing group

DoD:
A member in the new group is able to update the monthly cost value.

**Comment by nilsgstrabo** [comment]
- Renamed existing unused group: https://portal.azure.com/#view/Microsoft_AAD_IAM/GroupDetailsMenuBlade/~/Overview/groupId/ad4f6a93-79fb-4a6e-9861-e280bf6cb4e6/menuId/
